<a href="https://colab.research.google.com/github/Alex-Kurian/Python-Basics/blob/main/PythonBasics17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
values=np.random.randint(10,20,(6,3))
print(values)
print("*****")
print(values[0][1])
print(values[3][1])

[[13 17 14]
 [13 18 10]
 [15 12 14]
 [14 13 13]
 [13 18 18]
 [12 15 19]]
*****
17
13


In [2]:
print(values[1:4])

[[13 18 10]
 [15 12 14]
 [14 13 13]]


In [3]:
print(values[:4])
print(values[0:])

[[13 17 14]
 [13 18 10]
 [15 12 14]
 [14 13 13]]
[[13 17 14]
 [13 18 10]
 [15 12 14]
 [14 13 13]
 [13 18 18]
 [12 15 19]]


In [4]:
print(values[2],[2])

[15 12 14] [2]
